image: registry.gitlab.com/flokno/hilde:vibes

before_script:
  - flake8
  - cp vibes/templates/config_files/vibesrc.template ~/.vibesrc
  - poetry install
  - pip install https://gitlab.com/ase/ase/-/archive/master/ase-master.tar.gz
  - pip list

default:
  script:
    - pytest --cov --cov-config=setup.cfg tests/ --ignore tests/fireworks/

fireworks:
  when: manual
  before_script:
    - poetry install -E fireworks
    - service mongodb start --ipv6
    - cp vibes/templates/config_files/fireworksrc.template ~/.fireworksrc
  script:
    - pytest tests/fireworks

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - release
