# image: registry.gitlab.com/vibes-developers/vibes:test
image: continuumio/miniconda3

# https://dev.to/waylonwalker/installing-miniconda-on-linux-from-the-command-line-4ad7

before_script:
  
#   - gfortran --version
#   - flake8
#   - cp vibes/templates/config_files/vibesrc.template ~/.vibesrc
#   - mkdir -p ~/miniconda3
#   - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
#   - bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
#   - ~/miniconda3/bin/conda init bash
#   - ls ~
#   - source ~/.bashrc
#   - bash
#   - ~/miniconda3/bin/conda activate base
  - python --version
  - conda env list
  - conda list

#   - pip install poetry==1.1.4
#   - pip install poetry-core==1.0.0
  - pip list
  - ls /builds/vibes-developers/vibes/vibes/helpers/supercell
  - pip install -U pip
  - pip install -U numpy
  - pip install .
  - ls /builds/vibes-developers/vibes/vibes/helpers/supercell
  - echo $LD_LIBRARY_PATH
#  - poetry install
#  - pip install https://gitlab.com/ase/ase/-/archive/master/ase-master.tar.gz
  - pip list

default:
  script:
    - pytest --cov --cov-config=setup.cfg tests/ --ignore tests/fireworks/ --ignore tests/aims/
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t 698c45df-99fa-49a3-a353-451e54c537f7

fireworks:
  when: manual
  before_script:
    - poetry install -E fireworks
    - service mongodb start --ipv6
    - cp vibes/templates/config_files/fireworksrc.template ~/.fireworksrc
  script:
    - pytest tests/fireworks

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
  - docs
  - joss
