image: registry.gitlab.com/flokno/hilde:vibes

before_script:
  - cp vibes/templates/config_files/vibesrc.template ~/.vibesrc
  - poetry install
  - flake8 vibes
  - flake8 tests

default:
  script:
    - pytest --cov --cov-config=setup.cfg tests/ --ignore tests/fireworks/

fireworks:
  when: manual
  script:
    - service mongodb start --ipv6
    - pip install fireworks
    - pytest tests/fireworks
