image: registry.gitlab.com/flokno/hilde:update

before_script:
  - cp hilde.cfg.template hilde.cfg
  - pip install .
  - jtest="jupyter nbconvert --execute"
  - service mongodb start --ipv6
  - python --version

all_tests:
  script:
    - python $CI_PROJECT_DIR/tests/hashes/hashes.py
    - cd $CI_PROJECT_DIR/tests/commensurate_qpoints; python test_lattice_points.py
    - cd ../phonopy; python run_phonopy.py
    - python run_phono3py.py
    - cd ../md; python run_md.py
    - cd ../harmonic_analysis; python mode_projection.py
    - cd ../phonon_db; python phonon_db.py; python phonon_db.py;
    - cd ../fireworks; python fireworks_test.py
    - cd $CI_PROJECT_DIR/examples/devel
    - $jtest trajectory/pretty_json.ipynb
    - $jtest trajectory/read_trajectory.ipynb
    - python material_fingerprints/material_fingerprints.py

# devel:
#   script:



