# image: registry.gitlab.com/vibes-developers/vibes:test
image: continuumio/miniconda3

before_script:
  - pip install flake8 flake8-bugbear flake8-comprehensions pytest pytest-cov pytest-xdist 
  - flake8
  - conda install -c conda-forge numpy scipy gfortran phonopy==2.8.1
  - pip install .
  - pip list

default:
  script:
    - cp vibes/templates/config_files/vibesrc.template ~/.vibesrc
    - pytest --cov --cov-config=setup.cfg --ignore tests/fireworks/ --ignore tests/aims/ tests/ 
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t 698c45df-99fa-49a3-a353-451e54c537f7

fireworks:
#  when: manual
#  before_script:
    # - poetry install -E fireworks
    # - service mongodb start --ipv6
  script:
    # - conda install -c conda-forge fireworks 
    - pip install FireWorks
    - cp vibes/templates/config_files/fireworksrc.template ~/.fireworksrc
    - pytest tests/fireworks

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
  - docs
  - joss
