image: registry.gitlab.com/vibes-developers/vibes:default

before_script:
  - flake8
  - cp vibes/templates/config_files/vibesrc.template ~/.vibesrc
  - poetry install
  - pip install https://gitlab.com/ase/ase/-/archive/master/ase-master.tar.gz
  - pip list

default:
  script:
    - pytest --cov --cov-config=setup.cfg tests/ --ignore tests/fireworks/ --ignore tests/aims/
  after_script:
    - bash <(curl -s https://codecov.io/bash) -t 698c45df-99fa-49a3-a353-451e54c537f7

fireworks:
  when: manual
  before_script:
    - poetry install -E fireworks
    - service mongodb start --ipv6
    - cp vibes/templates/config_files/fireworksrc.template ~/.fireworksrc
  script:
    - pytest tests/fireworks

pages:
  script:
  - mkdocs build
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
  - docs
  - joss
