python_3_tests:
  image: python:3
  script:
    # manually install extra deps
    - apt-get update
    - apt-get install -yq gfortran
    - pip install numpy scipy matplotlib
    - pip install ase phonopy spglib
    - pip install .
    - python --version
    - cd $CI_PROJECT_DIR/examples/phonons
    - jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 --output output.ipynb phonopy.ipynb
