image: registry.gitlab.com/flokno/hilde:default

before_script:
  - cp hilde/templates/config_files/hilderc.template ~/.hilderc
  - poetry update
  - poetry install
  - cd $CI_PROJECT_DIR/tests

default:
  script:
    - pytest --ignore fireworks
    - cd cli; bash test_cli.sh
    - cd ../phonopy; python run_phonopy.py
    - cd ../harmonic_analysis; python mode_projection.py
    - cd $CI_PROJECT_DIR/examples/devel
    - python material_fingerprints/material_fingerprints.py

fireworks:
  when: manual
  script:
    - service mongodb start --ipv6
    - pip install fireworks
    - pytest fireworks
    - cd $CI_PROJECT_DIR/tests/phonon_db; python phonon_db.py; python phonon_db.py;
