site_name: FHI-vibes

repo_url: https://gitlab.com/flokno/hilde

copyright: 'Copyright &copy; 2020 Florian Knoop'

theme:
    name: 'material'
    palette:
        primary: 'Teal'
        accent: 'Blue Grey'
    logo: 'images/FV.svg'
    favicon: 'images/FV.svg'
    include_search_page: false
    feature:
        tabs: true

    font:
        text: 'Open Sans'
        code: 'Droid Sans Mono'

nav:
    - FHI-vibes: 
        - Getting Started: README.md
        - License: license.md
    - Tutorial: 
        - Tutorial/0_intro.md
        - Tutorial/acknowledgments.md
        - Tutorial/references.md

        
plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
    - toc:
        permalink: "#"
    - pymdownx.arithmatex
    - footnotes
    - admonition
    
extra_javascript:
  - 'javascripts/mathjax.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  

extra:
  social:
    - type: gitlab
      link: https://gitlab.com/flokno/hilde
    - type: twitter
      link: https://twitter.com/floknoo
      
