#!/usr/bin/env python3.6

from hilde.parsers import read_output
from argparse import ArgumentParser as argpars
# from pathlib import Path
import os

parser = argpars(description='Read geometry and print some symmetry info')
parser.add_argument('geom'                , type=str  , help='geometry input file')
parser.add_argument('-t', '--tolerance'   , type=float, default=1e-5,
                    help='symmetry tolerance (symprec)')
parser.add_argument('--aimsout', nargs='?', type=str  , default=None, const='-1',
                    help='use aims output file')
parser.add_argument('--format', default='aims', 
                    help='which format should ASE use to read file?')
args = parser.parse_args()

### Greet
fname=args.geom
cell = read_output(fname, symprec=args.tolerance, format=args.format)
cell.inform(fname=fname)
