#!/usr/bin/env python3.6

from hilde.parsers import read_aims
from argparse import ArgumentParser as argpars
# from pathlib import Path
import os

parser = argpars(description='Read geometry and print some symmetry info')
parser.add_argument('geom'                , type=str  , help='geometry input file')
parser.add_argument('-t', '--tolerance'   , type=float, default=1e-5,
    help='symmetry tolerance (symprec)')
parser.add_argument('--aimsout', nargs='?', type=str  , default=None, const='-1',
                help='use aims output file')
args = parser.parse_args()

### Greet
fname=args.geom
cell = read_aims(fname, symprec=args.tolerance)
cell.inform(fname=fname)
